spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER_NAME}
    password: ${PASSWORD}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework: info
    com.hobbyhop: debug
    org.springframework.security: trace

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
