spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {{USER_NAME}}
    password: {{PASSWORD}}
    url: jdbc:mysql://{{HOST}}:{{PORT}}/{{DATABASE_NAME}}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework: info
    com.sparta: debug
    org.springframework.security: trace

jwt:
  secret:
    key: {{JWT_SECRET_KEY}}
