spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER_NAME}
    password: ${PASSWORD}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework: info
    com.hobbyhop: debug
    org.springframework.security: debug

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false