spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    url: ${RDS_HOST}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework: info
    com.hobbyhop: debug
    org.springframework.security: debug

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      accessKey: ${ACCESS_KEY_ID}
      secretKey: ${ACCESS_KEY_SECRET}
    region:
      static: ${REGION}
      auto: false
