spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${{ secrets.RDS_USERNAME }}
    password: ${{ secrets.RDS_PASSWORD }}
    url: ${{ secrets.RDS_HOST }}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework: info
    com.hobbyhop: debug
    org.springframework.security: debug

jwt:
  secret:
    key: ${{ secrets.JWT_SECRET_KEY }}

cloud:
  aws:
    s3:
      bucket: ${{ secrets.S3_BUCKET_NAME }}
    credentials:
      accessKey: ${{ secrets.ACCESS_KEY_ID }}
      secretKey: ${{ secrets.ACCESS_KEY_SECRET }}
    region:
      static: ${{ secrets.REGION }}
      auto: false
